# ----------------------------------
# Stage 1: prepare ffmpeg
# ----------------------------------

FROM python:3.13-slim AS ffmpeg

USER root

RUN apt-get update && apt-get install -y \
  ffmpeg \
  && rm -rf /var/lib/apt/lists/*

# ----------------------------------
# Stage 2: prepare whisper model
# ----------------------------------

FROM python:3.13-slim AS whisper

USER root

RUN pip install --no-cache-dir huggingface_hub

RUN mkdir -p /root/.cache/whisper
RUN python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='openai/whisper-large-v3-turbo', local_dir='/root/.cache/whisper')"

# ----------------------------------
# Stage 3: install Python dependencies
# ----------------------------------

FROM python:3.13-slim AS deps

WORKDIR /autumn

USER root

COPY src/backend/requirements.txt src/backend/requirements.txt

RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r src/backend/requirements.txt

# ----------------------------------
# Stage 4: prepare project
# ----------------------------------

FROM python:3.13-slim

WORKDIR /autumn

USER root

RUN apt-get update && apt-get install -y \
  curl \
  htop \
  iproute2 \
  && rm -rf /var/lib/apt/lists/*

# copy python deps
COPY --from=deps /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=deps /usr/local/bin /usr/local/bin

# copy whisper deps
RUN mkdir -p /root/.cache/whisper
COPY --from=whisper /root/.cache/whisper /root/.cache/whisper
COPY --from=ffmpeg /usr/bin/ffmpeg /usr/bin/ffmpeg

COPY src/backend ./src/backend