# ----------------------------------
# Stage 1: prepare node_modules
# ----------------------------------

FROM node:22-alpine AS node

WORKDIR /autumn

USER root

COPY src/frontend ./src/frontend
COPY src/frontend/package.json ./package.json
RUN npm install -g pnpm
RUN pnpm install

# ----------------------------------
# Stage 2: prepare project
# ----------------------------------

FROM node:22-alpine

WORKDIR /autumn/src/frontend

USER root

COPY --from=node /autumn/package.json .
COPY --from=node /autumn/src/frontend .
COPY --from=node /autumn/node_modules /autumn/src/frontend/node_modules
RUN npm install -g pnpm
RUN pnpm run build